// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/lloydlobo/go-headcount/templates/components"

func Base() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\" data-framework=\"htmx\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Title(false).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<noscript><div style=\"color: red\"><p>JavaScript is disabled or not supported in your browser.</p><p>Please enable JavaScript to view this page.</p></div></noscript><link rel=\"stylesheet\" href=\"/static/css/missing.min.css\"><link rel=\"stylesheet\" href=\"/static/css/style.css\"><!-- This src /static/js/missing.css.overflow-nav.min.js is minified and compiled file from https://unpkg.com/missing.css@1.1.1/dist/js/overflow-nav.js, that also imports helpers from 19.js --><script type=\"module\" src=\"/static/js/missing.css.overflow-nav.min.js\"></script><script type=\"text/hyperscript\" src=\"/static/hs/start-me-up._hs\"></script><script type=\"text/hyperscript\" src=\"/static/hs/main._hs\"></script><script src=\"/static/js/htmx.min.js\"></script><script defer src=\"/static/js/_hyperscript.min.js\"></script><script defer src=\"https://unpkg.com/alpinejs-notify@latest/dist/notifications.min.js\"></script><script defer src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js\"></script><script defer type=\"module\" src=\"https://unpkg.com/missing.css@1.1.1/dist/js/menu.js\"></script><script defer src=\"https://unpkg.com/htmx.org/dist/ext/debug.js\"></script><script defer src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script><script defer type=\"text/javascript\">\n                htmx.logAll();\n            </script></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Navbar(false).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"mainContainer\" hx-boost=\"true\" hx-target=\"mainContainer\" hx-swap=\"innerHTML\" class=\"flex flex-col gap-8 !w-full items-center my-10\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"toast-container\" class=\"fixed bottom-0 right-0 flex flex-col gap-2 p-3\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
