// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Navbar(swapOob bool) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav id=\"navbarContainer\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if swapOob {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" hx-swap-oob=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"flex justify-center items-center py-2 top-0 bg-neutral-700 z-50 md:flex-nowrap flex-wrap\"><div class=\"w-5/6 md:w-1/2\"><div class=\"flex\"><div class=\"flex md:flex-nowrap flex-wrap items-center justify-between w-full mr-auto ml-auto\"><a class=\"text-xl py-[0.3125rem] mr-4 no-highlights\" href=\"/\">headcount</a> <input class=\"peer hidden\" type=\"checkbox\" id=\"navbar-check\"> <label class=\"md:hidden\" for=\"navbar-check\">Menu</label><div id=\"navbar\" class=\"flex md:basis-auto basis-full flex-grow-[1] items-center collapsed md:!h-auto md:!flex\"><ul class=\"flex flex-col pl-0 mb-0 list-none mt-2 md:mt-0 me-auto md:flex-row\"><li>About</li></ul></div></div></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
